### ISSUE TITLE
PCB file?

### ISSUE THREAD

**Issue by samuk** [maitesam/Raspberry-Pi-Pico-Breakout-V2.0#1]
Hi I can't spot the eagle/kicad/whatever files, are they available please?

**Comment by aitesam961** [comment]
Hi @samuk !
I added the **Directories** to make navigation through files easier. Please check the commit # https://github.com/aitesam961/Raspberry-Pi-Pico-Breakout-V2.0/commit/040b28a1914f7811b4c5d442cd79ba5c8db69155 
Please note that the source files relate to EasyEDA Standard. Easily import-able in EasyEDA PRO as well. Both of which are freeware. https://easyeda.com/

This is a community driven project and if you make any improvements or bug fixes, please create a pull request to the upstream as well. 
Thanks
